import { ArrowDownRight, ArrowRight, CalendarDays, ChevronRight, Plus, Scale, TrendingUp, Utensils } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Modal } from '../components/Modal';
import { EmptyState } from '../components/Ui';
import { PLAN_LABEL } from '../constants';
import { db, touchRecentFood } from '../db/database';
import type { AppData } from '../hooks/useAppData';
import { recalculateSnapshot } from '../services/snapshots';
import type { DailySnapshot, MealEntry } from '../types';
import { addDays, formatFriendlyDate, parseLocalDate, toLocalDateKey } from '../utils/date';
import { calculate15DayAverageWeight } from '../utils/weight';
import { roundKcal, roundSmart } from '../utils/format';
import { WeightModal } from './TodayPage';

type Range = 7 | 30 | 90 | 99999; type Metric = 'calories'|'protein'|'carbs'|'fat';
const metricConfig = { calories: ['热量','caloriesKcal','targetCalories','kcal'], protein: ['蛋白质','proteinG','proteinTarget','g'], carbs: ['碳水','carbsG','carbsTarget','g'], fat: ['脂肪','fatG','fatTarget','g'] } as const;

export function HistoryPage({ data, reload, toast }: { data: AppData; reload: () => Promise<void>; toast: (text: string) => void }) {
  const [range, setRange] = useState<Range>(30); const [metric, setMetric] = useState<Metric>('calories'); const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const today = toLocalDateKey(); const start = range === 99999 ? '0000-01-01' : addDays(today, -(range - 1));
  const allDates = useMemo(() => [...new Set([...data.weights.map(w => w.date), ...data.meals.map(m => m.date)])].filter(date => date >= start && date <= today).sort(), [data.weights, data.meals, start, today]);
  const snapshotMap = new Map(data.snapshots.map(s => [s.date, s]));
  const weightData = data.weights.filter(w => w.date >= start && w.date <= today).sort((a,b) => a.date.localeCompare(b.date)).map(w => ({ date: w.date.slice(5).replace('-','/'), fullDate: w.date, weight: w.weightKg, average: calculate15DayAverageWeight(data.weights, w.date) }));
  const nutritionData = allDates.map(date => { const items = data.meals.filter(m => m.date === date); const snap = snapshotMap.get(date); const sum = (key: keyof MealEntry) => items.reduce((total, item) => total + Number(item[key] ?? 0), 0); return { date: date.slice(5).replace('-','/'), fullDate: date, caloriesKcal: sum('caloriesSnapshot'), proteinG: sum('proteinSnapshot'), carbsG: sum('carbsSnapshot'), fatG: sum('fatSnapshot'), targetCalories: snap?.targetCalories ?? 0, proteinTarget: snap?.proteinTarget ?? 0, carbsTarget: snap?.carbsTarget ?? 0, fatTarget: snap?.fatTarget ?? 0 }; });
  const currentAverage = calculate15DayAverageWeight(data.weights, today); const previousAverage = calculate15DayAverageWeight(data.weights.filter(w => w.date <= addDays(today,-15)), addDays(today,-15)); const change = currentAverage !== null && previousAverage !== null ? currentAverage - previousAverage : null;
  const [label, actualKey, targetKey, unit] = metricConfig[metric];

  return <div className="history-page page-enter"><header className="page-header"><div><p>让变化慢慢变得清晰</p><h1>历史</h1></div><span className="header-art"><TrendingUp size={24} /></span></header>
    <div className="range-tabs">{[[7,'7天'],[30,'30天'],[90,'90天'],[99999,'全部']].map(([value,label]) => <button key={value} className={range === value ? 'active' : ''} onClick={() => setRange(value as Range)}>{label}</button>)}</div>
    {allDates.length === 0 ? <EmptyState title="变化正在路上" text="记录几天后，这里就会出现你的变化趋势。" /> : <>
      <section className="average-change-card"><div><span>当前15日平均</span><strong>{currentAverage === null ? '—' : `${roundSmart(currentAverage,2)} kg`}</strong></div>{change !== null && <div className={change <= 0 ? 'down' : 'up'}><ArrowDownRight size={20} /><span>较前15日</span><strong>{change > 0 ? '+' : ''}{roundSmart(change,2)} kg</strong></div>}</section>
      <section className="chart-card"><div className="chart-title"><div><Scale size={19} /><h2>体重趋势</h2></div><div className="legend"><span className="raw">每日体重</span><span className="avg">15日平均</span></div></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><LineChart data={weightData} margin={{ top: 12, right: 6, left: -26, bottom: 0 }}><CartesianGrid stroke="#ece9df" vertical={false} /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill:'#8a8c86' }} minTickGap={24} /><YAxis domain={['dataMin - 1','dataMax + 1']} axisLine={false} tickLine={false} tick={{ fontSize: 10, fill:'#aaa' }} /><Tooltip contentStyle={{ borderRadius:16, border:'1px solid #e8e5da', boxShadow:'0 10px 30px rgba(60,80,67,.1)' }} formatter={(value, name) => [`${roundSmart(Number(value),2)} kg`, name === 'average' ? '15日平均' : '每日体重']} labelFormatter={(_, payload) => payload?.[0]?.payload?.fullDate ?? ''} /><Line type="monotone" dataKey="weight" stroke="#b9c9be" strokeWidth={2} dot={{ r:3, fill:'#f8faf6', stroke:'#9eb6a5' }} connectNulls={false} /><Line type="monotone" dataKey="average" stroke="#5f9f77" strokeWidth={3} dot={{ r:3, fill:'#5f9f77' }} connectNulls /></LineChart></ResponsiveContainer></div></section>
      <section className="chart-card nutrition-chart"><div className="chart-title"><div><Utensils size={19} /><h2>营养趋势</h2></div></div><div className="metric-tabs">{(Object.keys(metricConfig) as Metric[]).map(key => <button key={key} className={metric === key ? 'active' : ''} onClick={() => setMetric(key)}>{metricConfig[key][0]}</button>)}</div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><BarChart data={nutritionData} margin={{ top: 15, right: 4, left: -28, bottom: 0 }}><CartesianGrid stroke="#f0ece2" vertical={false} /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fontSize:11, fill:'#8a8c86' }} minTickGap={24} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize:10, fill:'#aaa' }} /><Tooltip contentStyle={{ borderRadius:16, border:'1px solid #e8e5da' }} formatter={(value, name) => [`${roundSmart(Number(value))} ${unit}`, name === actualKey ? `实际${label}` : `目标${label}`]} /><Bar dataKey={targetKey} fill="#dfe9e1" radius={[6,6,0,0]} maxBarSize={16} /><Bar dataKey={actualKey} fill="#f0b985" radius={[6,6,0,0]} maxBarSize={16} /></BarChart></ResponsiveContainer></div><div className="bar-legend"><span>实际{label}</span><span>当日目标</span></div></section>
      <section className="daily-history"><div className="section-heading"><div><CalendarDays size={20} /><h2>每日记录</h2></div></div>{allDates.slice().reverse().map(date => { const weight = data.weights.find(w => w.date === date); const items = data.meals.filter(m => m.date === date); const actualKcal = items.reduce((s,m) => s + m.caloriesSnapshot, 0); const snap = snapshotMap.get(date); return <button className="day-row" key={date} onClick={() => setSelectedDate(date)}><div><strong>{formatFriendlyDate(date)}</strong><span>{weight ? `${roundSmart(weight.weightKg,2)} kg` : '未记录体重'} · {snap ? PLAN_LABEL[snap.plan] : '暂无目标'}</span></div><div><b>{roundKcal(actualKcal)}{snap ? ` / ${roundKcal(snap.targetCalories)}` : ''} kcal</b><ChevronRight size={18} /></div></button>; })}</section>
    </>}
    {selectedDate && <HistoryDetail date={selectedDate} data={data} snapshot={snapshotMap.get(selectedDate)} onClose={() => setSelectedDate(null)} reload={reload} toast={toast} />}
  </div>;
}

function HistoryDetail({ date, data, snapshot, onClose, reload, toast }: { date: string; data: AppData; snapshot?: DailySnapshot; onClose: () => void; reload: () => Promise<void>; toast: (text: string) => void }) {
  const [weightEdit, setWeightEdit] = useState(false); const weight = data.weights.find(w => w.date === date); const meals = data.meals.filter(m => m.date === date); const actual = { calories: meals.reduce((s,m) => s+m.caloriesSnapshot,0), protein: meals.reduce((s,m) => s+m.proteinSnapshot,0), carbs: meals.reduce((s,m) => s+m.carbsSnapshot,0), fat: meals.reduce((s,m) => s+m.fatSnapshot,0) };
  const addAgain = async (entry: MealEntry) => { const today = toLocalDateKey(); const clone = { ...entry, id: undefined, date: today, createdAt: Date.now() }; await db.meals.add(clone); await touchRecentFood(entry.foodId); await recalculateSnapshot(today); await reload(); toast(`已把“${entry.foodNameSnapshot}”添加到今天`); };
  return <Modal title="历史详情" onClose={onClose} wide><div className="history-detail"><p className="eyebrow">{formatFriendlyDate(date,true)}</p><div className="detail-weight"><div><span>体重</span><strong>{weight ? `${roundSmart(weight.weightKg,2)} kg` : '未记录'}</strong></div><button onClick={() => setWeightEdit(true)}>编辑</button></div>
    {snapshot ? <><div className="detail-highlights"><div><span>15日平均</span><strong>{roundSmart(snapshot.average15DayKg,2)} kg</strong></div><div><span>基础代谢参考</span><strong>{roundKcal(snapshot.bmr)} kcal</strong></div><div><span>当日方案</span><strong>{PLAN_LABEL[snapshot.plan]}</strong></div></div><p className="tiny-note">基础代谢仅作为参考，不参与每日营养目标计算。算法版本：{snapshot.algorithmVersion}</p><div className="detail-nutrition"><CompareRow label="热量" actual={actual.calories} target={snapshot.targetCalories} unit="kcal" /><CompareRow label="蛋白质" actual={actual.protein} target={snapshot.proteinTarget} unit="g" /><CompareRow label="碳水" actual={actual.carbs} target={snapshot.carbsTarget} unit="g" /><CompareRow label="脂肪" actual={actual.fat} target={snapshot.fatTarget} unit="g" /></div></> : <p className="inline-empty">当天没有足够体重数据生成营养目标。</p>}
    <h3 className="detail-meals-title">当天饮食</h3>{meals.length ? meals.map(item => <div className="detail-meal" key={item.id}><div><strong>{item.foodNameSnapshot}</strong><span>{roundSmart(item.amount)}{item.unit} · {roundKcal(item.caloriesSnapshot)} kcal</span></div><button onClick={() => void addAgain(item)}><Plus size={15} /> 再次添加</button></div>) : <p className="inline-empty">当天没有饮食记录。</p>}
    {weightEdit && <WeightModal date={date} initialKg={weight?.weightKg} unit={data.profile!.weightUnit} onClose={() => setWeightEdit(false)} onSaved={async () => { await reload(); toast('历史体重已更新'); }} />}
  </div></Modal>;
}
function CompareRow({ label, actual, target, unit }: { label: string; actual: number; target: number; unit: string }) { const p = target > 0 ? Math.min(100, actual/target*100) : 0; return <div className="compare-row"><div><span>{label}</span><strong>{roundSmart(actual)} / {roundSmart(target)} {unit}</strong></div><i><b style={{width:`${p}%`}} /></i></div>; }
